apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-datadir-consul-0
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: consul
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-datadir-consul-1
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: consul
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-datadir-consul-2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: consul
      podindex: "2"
